spring.application.name=echo-spring
server.port=9000
server.shutdown=graceful
server.tomcat.threads.max=2000
server.tomcat.max-connections=2000
# For enable Logging just uncomment the following lines
#server.error.include-exception=true
#server.tomcat.accesslog.enabled=true
#logging.level.org.apache.coyote.http11=DEBUG
